# On commence à partir de l'image officielle Ubuntu
FROM ubuntu:latest

# On met à jour les paquets (logiciels) du système
RUN apt-get update && apt-get upgrade -y

# Quand on lance le conteneur, il doit dire "Hello, World!"
CMD ["echo", "Hello, World!"]
